# Site settings
title: peter ashwell
email: peter.w.ashwell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software developer, with computation-wise interests in
  web frameworks, computer vision, and natural language processing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://peterashwell.com" # the base hostname & protocol for your site
twitter_username: peterashwell 
github_username:  peterashwell

# Build settings
markdown: kramdown
